import * as React from 'react';
import { format, parseISO } from 'date-fns';
import { ExternalLink, Maximize2 } from 'lucide-react';
import { Button } from '../../../../components/ui/button';
import type { EditablePostField, MediaFormat, MediaGoal, MediaPost } from '../../../../lib/types/media';
import { dotStyle } from '../../../../lib/media/badge-color';
import { accentFor, type ColorMode } from '../../../../lib/media/color-mode';
import { normalizeReferenceUrl } from '../../../../lib/media/reference-url';
import { PostedBadge } from '../../_components/media-badges';
import { ReferenceIconLink } from '../../_components/reference-link';
import { InlineDate, InlineSelect, InlineText } from './inline-fields';

const day = (value: string | null | undefined) => value?.slice(0, 10) ?? '';

interface WeekGroup {
  id: string;
  label: string;
  hint: string | null;
  posts: MediaPost[];
}

/**
 * `week_no` is generated by the database, so it is the authority whenever present.
 * A row with a date but no computed week still gets a sensible bucket, and undated
 * posts collect in one "Unscheduled" group rather than disappearing.
 *
 * Insertion order is preserved, and `getPosts()` orders by `post_date ASC NULLS
 * LAST`, so the groups come out chronologically with Unscheduled last.
 */
function groupByWeek(posts: MediaPost[]): WeekGroup[] {
  const groups = new Map<string, WeekGroup>();

  for (const post of posts) {
    const hasWeek = typeof post.week_no === 'number';
    const date = day(post.post_date);
    const id = hasWeek ? `w-${post.week_no}` : date ? `d-${date.slice(0, 7)}` : 'unscheduled';

    if (!groups.has(id)) {
      groups.set(id, {
        id,
        label: hasWeek
          ? (post.week_label?.trim() || `Week ${post.week_no}`)
          : date
            ? format(parseISO(date), 'MMMM yyyy')
            : 'Unscheduled',
        // When a custom label replaced the title, the number survives as a hint.
        hint: hasWeek && post.week_label?.trim() ? `Week ${post.week_no}` : null,
        posts: [],
      });
    }
    groups.get(id)!.posts.push(post);
  }

  return Array.from(groups.values());
}

interface PostsListViewProps {
  posts: MediaPost[];
  goals: MediaGoal[];
  formats: MediaFormat[];
  colorMode: ColorMode;
  onSaveField: (postId: string, field: EditablePostField, value: string | null) => Promise<boolean>;
  onOpen: (post: MediaPost) => void;
}

const TH = 'whitespace-nowrap px-3 py-2.5 text-[11px] font-semibold uppercase tracking-[0.06em] text-black/40';

export function PostsListView({ posts, goals, formats, colorMode, onSaveField, onOpen }: PostsListViewProps) {
  const groups = React.useMemo(() => groupByWeek(posts), [posts]);

  const goalMap = React.useMemo(() => new Map(goals.map((g) => [g.key, g])), [goals]);
  const formatMap = React.useMemo(() => new Map(formats.map((f) => [f.key, f])), [formats]);

  const goalOptions = React.useMemo(
    () => goals.map((g) => ({ key: g.key, label: g.label, color: g.color })),
    [goals],
  );
  const formatOptions = React.useMemo(
    () => formats.map((f) => ({ key: f.key, label: f.label, color: f.color })),
    [formats],
  );

  return (
    <div className="overflow-hidden rounded-2xl border border-black/[0.07] bg-white">
      <div className="overflow-x-auto">
        <table className="w-full min-w-[1320px] border-collapse text-left">
          <thead className="sticky top-0 z-10 bg-white/95 backdrop-blur-sm">
            <tr className="border-b border-black/[0.07]">
              <th scope="col" className={TH}>Date</th>
              <th scope="col" className={TH}>Day</th>
              <th scope="col" className={TH}>Goal</th>
              <th scope="col" className={TH}>Format</th>
              <th scope="col" className={TH}>Objective</th>
              <th scope="col" className={TH}>Text on Visual / Video Script</th>
              <th scope="col" className={TH}>Caption</th>
              <th scope="col" className={TH}>CTA</th>
              <th scope="col" className={TH}>Media Link</th>
              <th scope="col" className={TH}>Reference</th>
              <th scope="col" className={TH}>Posted</th>
              <th scope="col" className={TH} />
            </tr>
          </thead>

          <tbody>
            {groups.map((group) => (
              <React.Fragment key={group.id}>
                <tr>
                  <th
                    scope="colgroup"
                    colSpan={12}
                    className="border-y border-black/[0.05] bg-black/[0.018] px-3 py-2 text-left"
                  >
                    <span className="flex items-center gap-2">
                      <span className="text-[12px] font-semibold tracking-[-0.008em] text-black/70">
                        {group.label}
                      </span>
                      {group.hint && <span className="text-[11px] font-medium text-black/30">{group.hint}</span>}
                      <span className="ml-auto rounded-full bg-black/[0.05] px-1.5 text-[10.5px] font-semibold tabular-nums text-black/45">
                        {group.posts.length}
                      </span>
                    </span>
                  </th>
                </tr>

                {group.posts.map((post) => {
                  const date = day(post.post_date);
                  const accent = accentFor(
                    colorMode,
                    post.goal_key ? goalMap.get(post.goal_key) : undefined,
                    post.format_key ? formatMap.get(post.format_key) : undefined,
                  );
                  return (
                    <tr
                      key={post.id}
                      className="group/row border-b border-black/[0.04] align-top transition-colors duration-150 last:border-b-0 hover:bg-black/[0.015]"
                    >
                      <td className="px-1 py-2">
                        <div className="flex items-center gap-1.5">
                          {/* Reads as a rail, not a bullet: it belongs to the row. */}
                          <span
                            aria-hidden
                            title={accent?.label}
                            className="h-6 w-[3px] shrink-0 rounded-full"
                            style={dotStyle(accent?.color)}
                          />
                          <InlineDate
                            value={date || null}
                            ariaLabel="Post date"
                            onSave={(v) => onSaveField(post.id, 'post_date', v)}
                          />
                        </div>
                      </td>

                      <td className="whitespace-nowrap px-3 py-3.5 text-[12.5px] text-black/45">
                        {date ? format(parseISO(date), 'EEEE') : '—'}
                      </td>

                      <td className="px-2 py-2">
                        <InlineSelect
                          showDot
                          value={post.goal_key}
                          options={goalOptions}
                          placeholder="No goal"
                          ariaLabel="Goal"
                          onSave={(v) => onSaveField(post.id, 'goal_key', v)}
                        />
                      </td>

                      <td className="px-2 py-2">
                        <InlineSelect
                          value={post.format_key}
                          options={formatOptions}
                          placeholder="No format"
                          ariaLabel="Format"
                          onSave={(v) => onSaveField(post.id, 'format_key', v)}
                        />
                      </td>

                      <td className="min-w-[180px] px-1 py-2">
                        <InlineText
                          value={post.objective}
                          placeholder="Add objective"
                          ariaLabel="Objective"
                          onSave={(v) => onSaveField(post.id, 'objective', v)}
                        />
                      </td>

                      <td className="min-w-[220px] px-1 py-2">
                        <InlineText
                          multiline
                          value={post.visual_script}
                          placeholder="Add on-screen text or script"
                          ariaLabel="Text on visual or video script"
                          onSave={(v) => onSaveField(post.id, 'visual_script', v)}
                        />
                      </td>

                      <td className="min-w-[220px] px-1 py-2">
                        <InlineText
                          multiline
                          value={post.caption}
                          placeholder="Add caption"
                          ariaLabel="Caption"
                          onSave={(v) => onSaveField(post.id, 'caption', v)}
                        />
                      </td>

                      <td className="min-w-[130px] px-1 py-2">
                        <InlineText
                          value={post.cta}
                          placeholder="Add CTA"
                          ariaLabel="CTA"
                          onSave={(v) => onSaveField(post.id, 'cta', v)}
                        />
                      </td>

                      <td className="px-1 py-2">
                        <div className="flex items-start gap-1">
                          <InlineText
                            className="truncate"
                            value={post.media_link}
                            placeholder="Add link"
                            ariaLabel="Media link"
                            onSave={(v) => onSaveField(post.id, 'media_link', v)}
                          />
                          {post.media_link && (
                            <a
                              href={post.media_link}
                              target="_blank"
                              rel="noopener noreferrer"
                              aria-label="Open media link in a new tab"
                              className="mt-1.5 shrink-0 rounded-md p-1 text-black/30 transition-colors hover:bg-black/[0.05] hover:text-black/60"
                            >
                              <ExternalLink size={12} />
                            </a>
                          )}
                        </div>
                      </td>

                      <td className="px-1 py-2">
                        <div className="flex items-start gap-1">
                          <InlineText
                            className="truncate"
                            value={post.reference_url}
                            placeholder="Add reference"
                            ariaLabel="Reference link"
                            // Normalised here too, so the optimistic value in the
                            // grid is exactly what the server ends up storing.
                            onSave={(v) => onSaveField(post.id, 'reference_url', normalizeReferenceUrl(v))}
                          />
                          <ReferenceIconLink url={post.reference_url} className="mt-1.5" />
                        </div>
                      </td>

                      {/* Never editable here — Posted belongs to an admin. */}
                      <td className="px-3 py-3.5">
                        <PostedBadge posted={post.posted} />
                      </td>

                      <td className="px-3 py-3">
                        <Button
                          variant="ghost"
                          size="icon-sm"
                          aria-label="Open post details"
                          onClick={() => onOpen(post)}
                          className="opacity-0 transition-opacity duration-150 focus-visible:opacity-100 group-hover/row:opacity-100"
                        >
                          <Maximize2 size={13} strokeWidth={1.75} />
                        </Button>
                      </td>
                    </tr>
                  );
                })}
              </React.Fragment>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
