/**
 * Media section — social content planning.
 *
 * Lives in its own Postgres schema (`media`), reached through `mediaDb` in
 * src/lib/media/client.ts. Unrelated to the legacy `social` schema.
 */

// ─── Taxonomy ─────────────────────────────────────────────────────────────────

/** Rows of media.goals / media.formats. Read dynamically — never hardcode the keys. */
export interface MediaTaxonomyItem {
  key: string;
  label: string;
  color: string | null;
  is_active: boolean;
  sort_order: number;
}

/** Lookup built once per load so badges resolve without scanning the list. */
export type TaxonomyMap = Map<string, MediaTaxonomyItem>;

// ─── Ideas ────────────────────────────────────────────────────────────────────

export const IDEA_CATEGORIES = ['indoor', 'outdoor', 'graphic', 'reels', 'ugc', 'trending'] as const;
export type IdeaCategory = (typeof IDEA_CATEGORIES)[number];

export const IDEA_CATEGORY_LABELS: Record<IdeaCategory, string> = {
  indoor: 'Indoor',
  outdoor: 'Outdoor',
  graphic: 'Graphic',
  reels: 'Reels',
  ugc: 'UGC',
  trending: 'Trending',
};

export function asIdeaCategory(value: string | null | undefined): IdeaCategory {
  return IDEA_CATEGORIES.includes(value as IdeaCategory) ? (value as IdeaCategory) : 'indoor';
}

export interface MediaIdea {
  id: string;
  title: string | null;
  content: string | null;
  category: string;
  format_key: string | null;
  goal_key: string | null;
  /** Admin-only. Read-only in this dashboard — the server trigger rejects writes. */
  posted: boolean;
  /** Admin-only. Read-only in this dashboard — the server trigger rejects writes. */
  is_approved: boolean;
  note: string | null;
  converted_post_id: string | null;
  created_by: string | null;
  created_at: string;
  updated_at: string;
}

/** Exactly the columns staff may write. Mirrors IDEA_WRITABLE_COLUMNS. */
export interface IdeaDraft {
  title: string | null;
  content: string | null;
  category: string;
  format_key: string | null;
  goal_key: string | null;
  note: string | null;
}

// ─── Posts ────────────────────────────────────────────────────────────────────

export interface MediaPost {
  id: string;
  post_date: string | null;
  /** Generated by Postgres from post_date. Read-only. */
  week_no: number | null;
  week_label: string | null;
  goal_key: string | null;
  format_key: string | null;
  objective: string | null;
  visual_script: string | null;
  caption: string | null;
  cta: string | null;
  media_link: string | null;
  /** Admin-only. Read-only in this dashboard — the server trigger rejects writes. */
  posted: boolean;
  source_idea_id: string | null;
  created_by: string | null;
  created_at: string;
  updated_at: string;
}

/** Exactly the columns staff may write. Mirrors POST_WRITABLE_COLUMNS. */
export interface PostDraft {
  post_date: string | null;
  week_label: string | null;
  goal_key: string | null;
  format_key: string | null;
  objective: string | null;
  visual_script: string | null;
  caption: string | null;
  cta: string | null;
  media_link: string | null;
  source_idea_id: string | null;
}

// ─── Influencers ──────────────────────────────────────────────────────────────

/**
 * `type`, `messaging_status` and `final_decision` are free text in Postgres — the
 * option lists (and their badge colours) live with the Influencers page that renders
 * them, so a new status is one edit away.
 */
export interface MediaInfluencer {
  id: string;
  name: string | null;
  /** Free text on purpose — "120K", "1.2M" and raw counts all appear. */
  followers_count: string | null;
  url: string | null;
  email_contact: string | null;
  type: string | null;
  country: string | null;
  notes: string | null;
  messaging_status: string | null;
  final_decision: string | null;
  created_by: string | null;
  created_at: string;
  updated_at: string;
}

/** Exactly the columns staff may write. Mirrors INFLUENCER_WRITABLE_COLUMNS. */
export interface InfluencerDraft {
  name: string | null;
  followers_count: string | null;
  url: string | null;
  email_contact: string | null;
  type: string | null;
  country: string | null;
  notes: string | null;
  messaging_status: string | null;
  final_decision: string | null;
}
