/**
 * Types for the `media` schema (separate from `public`, and unrelated to the
 * legacy `social` schema). Goals and formats are lookup *rows*, never constants —
 * their labels and colours are edited in the database.
 */

// ─── Lookups ──────────────────────────────────────────────────────────────────

export interface MediaLookup {
  key: string;
  label: string;
  /** Free-form CSS colour: hex, `rgb(…)`, or a named colour. May be null. */
  color: string | null;
  is_active: boolean;
  sort_order: number | null;
}

export type MediaGoal = MediaLookup;
export type MediaFormat = MediaLookup;

// ─── Tones (static accent palette for this section's own enums) ───────────────

export type Tone = 'slate' | 'sky' | 'violet' | 'amber' | 'rose' | 'emerald';

// ─── Ideas ────────────────────────────────────────────────────────────────────

export const IDEA_CATEGORIES = ['Indoor', 'Outdoor', 'Graphic', 'Reels', 'UGC', 'Trending'] as const;
export type IdeaCategory = (typeof IDEA_CATEGORIES)[number];

export interface MediaIdea {
  id: string;
  title: string;
  content: string | null;
  category: string | null;
  format_key: string | null;
  goal_key: string | null;
  /** Instagram link to the trend or example this is modelled on. */
  reference_url: string | null;
  /** Admin-only. Read-only here — a server trigger rejects staff writes. */
  posted: boolean;
  /** Admin-only. Read-only here — a server trigger rejects staff writes. */
  is_approved: boolean;
  note: string | null;
  /** Written only by `convertIdeaToPost`. */
  converted_post_id: string | null;
  created_by: string | null;
  created_at: string;
  updated_at: string | null;
}

/**
 * Exactly the columns this dashboard may write. `posted` and `is_approved` are
 * absent from the type, so they cannot reach a payload even by accident.
 */
export type IdeaInput = {
  id?: string;
  title: string;
  content: string | null;
  category: string | null;
  goal_key: string | null;
  format_key: string | null;
  note: string | null;
  reference_url: string | null;
};

// ─── Posts ────────────────────────────────────────────────────────────────────

export interface MediaPost {
  id: string;
  /** `yyyy-MM-dd`. */
  post_date: string | null;
  /** Generated by the DB — read-only. */
  week_no: number | null;
  week_label: string | null;
  goal_key: string | null;
  format_key: string | null;
  objective: string | null;
  visual_script: string | null;
  caption: string | null;
  cta: string | null;
  media_link: string | null;
  /** Instagram link to the trend or example this is modelled on. */
  reference_url: string | null;
  /** Admin-only. Read-only here — a server trigger rejects staff writes. */
  posted: boolean;
  /** Written only by `convertIdeaToPost`. */
  source_idea_id: string | null;
  created_by: string | null;
  created_at: string;
  updated_at: string | null;
}

export type PostInput = {
  id?: string;
  post_date: string | null;
  week_label: string | null;
  goal_key: string | null;
  format_key: string | null;
  objective: string | null;
  visual_script: string | null;
  caption: string | null;
  cta: string | null;
  media_link: string | null;
  reference_url: string | null;
};

export type EditablePostField = Exclude<keyof PostInput, 'id'>;

// ─── Influencers ──────────────────────────────────────────────────────────────

export const INFLUENCER_TYPES = [
  { value: 'Popular Influencer', label: 'Popular Influencer', tone: 'violet' },
  { value: 'Influencer', label: 'Influencer', tone: 'sky' },
  { value: 'UGC', label: 'UGC', tone: 'amber' },
] as const satisfies readonly { value: string; label: string; tone: Tone }[];

export const MESSAGING_STATUSES = [
  { value: 'Not Contacted', label: 'Not Contacted', tone: 'slate' },
  { value: 'Contacted', label: 'Contacted', tone: 'sky' },
  { value: 'Replied', label: 'Replied', tone: 'violet' },
  { value: 'In Talks', label: 'In Talks', tone: 'amber' },
  { value: 'No Reply', label: 'No Reply', tone: 'rose' },
] as const satisfies readonly { value: string; label: string; tone: Tone }[];

export const FINAL_DECISIONS = [
  { value: 'Pending', label: 'Pending', tone: 'slate' },
  { value: 'Approved', label: 'Approved', tone: 'emerald' },
  { value: 'Rejected', label: 'Rejected', tone: 'rose' },
  { value: 'On Hold', label: 'On Hold', tone: 'amber' },
] as const satisfies readonly { value: string; label: string; tone: Tone }[];

export interface MediaInfluencer {
  id: string;
  name: string;
  /** Text on purpose — "124K", "1.2M" and raw counts all appear. Never parsed. */
  followers_count: string | null;
  url: string | null;
  /** Email *or* phone; the UI switches `mailto:`/`tel:` on the presence of `@`. */
  email_contact: string | null;
  type: string | null;
  /** ISO 3166-1 alpha-2. */
  country: string | null;
  notes: string | null;
  messaging_status: string | null;
  final_decision: string | null;
  created_by: string | null;
  created_at: string;
  updated_at: string | null;
}

export type InfluencerInput = {
  id?: string;
  name: string;
  followers_count: string | null;
  url: string | null;
  email_contact: string | null;
  type: string | null;
  country: string | null;
  notes: string | null;
  messaging_status: string | null;
  final_decision: string | null;
};

// ─── Action results ───────────────────────────────────────────────────────────

export type ActionResult = { ok: boolean; error?: string };
export type SaveResult = ActionResult & { id?: string };
export type ConvertResult = ActionResult & { postId?: string; warning?: string };
